export const LOAD_MY_PLAYER_SUCCESS = 'LOAD_MY_PLAYER_SUCCESS';

export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS';
export const PLAYER_PRESENCE_UPDATED = 'PLAYER_PRESENCE_UPDATED';
export const PLAYER_ADDED = 'PLAYER_ADDED';

export const LOAD_GAME_SUCCESS = 'LOAD_GAME_SUCCESS';
export const SET_CURRENT_GAME = 'SET_CURRENT_GAME';
export const CREATED_NEW_GAME = 'CREATED_NEW_GAME';
export const GAME_ACTION_TAKEN = 'GAME_ACTION_TAKEN';
export const GAME_STATE_CHANGED = 'GAME_STATE_CHANGED';
export const GAME_PLAYER_MODE_CHANGED = 'GAME_PLAYER_MODE_CHANGED';
